```{r}
#This R markdown script plots the figures as they appear in Bijl et al., in review in ESSD, using the data frames as stored in https://github.com/bijlpeter83/DINOSTRAT.git. This markdown is to be used freely, but please cite the corresponding paper in ESSD when using the data.



library(caTools)
library(ggspatial)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggplot2)
library(tidyverse)
library(geoscale)
library(jcolors)
library(rgeos)
```

```{r}
#loading sites into R:
locations <- read_csv("https://raw.githubusercontent.com/bijlpeter83/DINOSTRAT/main/Paleolatitude.csv")
locations

#Selecting variables of interest to plot Figure 2
sites <- select(locations, location, long, lat, tier)
sites <- distinct(sites)
#to make sure the variables have the right format
sites$tier <- as.character(sites$tier)
sites

#Selecting variables of interest for Figure 3
paleolat <- select(locations, Source, Geography, location, Age, Paleolatitude, lower, upper, interpolated, Stable, tier)
#to make sure the variables have the right format:
paleolat$tier <- as.character(paleolat$tier)
paleolat$Paleolatitude <- as.numeric(paleolat$Paleolatitude)
paleolat$lower <- as.numeric(paleolat$lower)
paleolat$upper <- as.numeric(paleolat$upper)
paleolat

#adding the locations of surface sediment samples:
modernst <- read_csv("https://raw.githubusercontent.com/bijlpeter83/DINOSTRAT/main/modernst.csv")

```
```{r}
#setting a theme
theme_set(theme_bw())

#selcting input for the maps:
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

#plot the global map of sites used in this study (Figure 2):
ggplot(data = world) +
  geom_sf(color="black", fill="black")+
  coord_sf()+
  geom_point(modernst, mapping=aes(x=long, y=lat), color="grey", size = 0.1)+
  geom_point(sites, mapping = aes(x=long, y=lat, color = tier), size=1)+
  scale_color_jcolors()+
  xlab("Longitude") + ylab("Latitude") +
    ggtitle("Global map of calibrated dinocyst records", subtitle = paste0("(", length(unique(sites$location)), " sites)"))
ggsave("geography.pdf")

#plot the detailed map of sites in Europe:
ggplot(data = world) +
  geom_sf(color="black", fill="black")+
  geom_point(modernst, mapping=aes(x=long, y=lat), color="grey", size = 0.1)+
  geom_point(sites, mapping = aes(x=long, y=lat, color = tier), size=1)+
  scale_color_jcolors()+
  coord_sf(xlim = c(-30, 50), ylim = c(35, 70))+
  xlab("Longitude") + ylab("Latitude")+
  ggtitle("Detailed map of European calibrated dinoflagellate cyst records")
ggsave("geography_europs.pdf")


#plot the latitudinal and longitudinal histograms:
ggplot()+
  geom_histogram(sites, mapping = aes(x=long), bins = 36, fill = "red", color = "black")+
scale_x_continuous(limits=c(-180, 180), breaks = seq(-180, 180, 30))
ggsave("longitude distribution.pdf")

ggplot()+
  geom_histogram(sites, mapping=aes(x=lat), bins = 36, fill = "red", color = "black")+
  scale_x_continuous(limits=c(-90, 90), breaks = seq(-90, 90, 30))
ggsave("latitude distribution.pdf")
  

#I pasted these plots together in Illustrator, to make Figure 2

```
```{r}

#To plot Figure 3:
ggplot(paleolat)+
  geom_ribbon(mapping=aes(x=Age, ymin=lower, ymax=upper, group=location), alpha=0.1)+
  geom_line(mapping=aes(x=Age, y=Paleolatitude, color=tier, group=location, size = Stable), orientation = "x", lineend = "round")+
  scale_size_discrete(range=c(0.4, 0.8))+
  scale_x_continuous(name="Age (Ma; GTS2012)", breaks = seq(0, 250, 25), minor_breaks = seq(0, 250, 5), labels = seq(0, 250, 25))+
  scale_y_continuous(name = "Paleolatitude", breaks = seq(-90, 90, 30), minor_breaks = seq(-90, 90, 10), labels = seq(-90, 90, 30))+
  scale_color_jcolors()
ggsave("paleolat.pdf")

#and the time scale underneath:
ages <- seq(0,250, 10)
data <- seq(0,250,10)
data(biozones)
geoscalePlot(ages = ages, data= data, units = c("Age", "Epoch", "Period"))

#Both plots were collated in Illustrator

```

```{r}
#load fossil event data into R, and unite some columns:
sp_dat <- read_csv("https://raw.githubusercontent.com/bijlpeter83/DINOSTRAT/main/Dinoevents_Jan2021.csv")
sp_dat <- unite(sp_dat, Family, Subfamily, col="Family", sep=", ", na.rm=TRUE, remove = TRUE)
sp_dat <- unite(sp_dat, genus, species, subspecies, col = "taxa", sep= " ", na.rm=TRUE, remove=FALSE)

#load fossil events into R and unite some columns:
modernsp <- read_csv("https://raw.githubusercontent.com/bijlpeter83/DINOSTRAT/main/modernsp.csv")
modernsp <- unite(modernsp, Family, Subfamily, col="Family", sep=", ", na.rm=TRUE, remove = TRUE)
modernsp <- unite(modernsp, genus, species, subspecies, col = "taxa", sep= " ", na.rm=TRUE, remove=FALSE)

#join both datasets into 1:
sp_dat1 <- bind_rows(sp_dat, modernsp)

#separate FOs from LOs
FO_sp <- filter(sp_dat1, FO_LO=="FO")
LO_sp <- filter(sp_dat1, FO_LO=="LO")

#These will show the histograms of species and genera oldest FOs and youngest LOs as in Fig. 3:
Hist_FO <- filter(FO_sp%>%group_by(taxa), Age==max(Age))
Hist_LO <- filter(LO_sp%>%group_by(taxa), Age==min(Age))
Hist <- bind_rows(Hist_FO, Hist_LO)
  
Hist
Hist_GF <- filter(FO_sp%>%group_by(genus), Age==max(Age))
Hist_GL <- filter(LO_sp%>%group_by(genus), Age==min(Age))
Hist_G <- bind_rows(Hist_GF, Hist_GL)


ggplot()+
  geom_histogram(Hist_FO, mapping=aes(x=Age, y=..count..), bins = 125, fill="blue", alpha=0.5)+
  geom_histogram(Hist_LO, mapping=aes(x=Age, y=-..count..), bins = 125, fill="red3", alpha=0.5)+
  geom_histogram(Hist_GF, mapping=aes(x=Age, y=..count..), bins = 125, fill="blue")+
  geom_histogram(Hist_GL, mapping=aes(x=Age, y=-..count..), bins = 125, fill="red3")+
  scale_x_continuous(limits=c(0, 250), breaks = seq(0, 250, 25))+
  scale_y_continuous(limits=c(-80, 80))+
  theme(aspect.ratio = 0.5)
ggsave("hist_age2.pdf")


```
```{r}
#select the latitudinally synchronous FOs:
Fsp <- c(
  "Achomosphaera andalousiensis", "Adnatosphaeridium vittanum", "Aldorfia aldorfensis", "Alisocysta margarita", "Ambonosphaera calloviana", "Amiculosphaera umbracula", "Apectodinium augustum", "Apectodinium hyperacanthum", "Aprobolocysta eilema", "Areoligera gippingensis", "Areosphaeridium diktyoplokum", "Artemisiocysta cladodichotoma", "Ataxiodinium confusum", "Atopodinium polygonale", "Atopodinium prostatum",
  "Biorbifera johnwingii", "Barbatacysta pilosa", "Barssidinium evangelineae", "Batioladinium reticulatum",
  "Callaiosphaeridium trycherium", "Carpathodinium predae", "Carpatella cornuta", "Cerodinium pannuceum", "Cerodinium speciosum", "Cerodinium striatum", "Cerodinium medcalfii", "Charlesdowniea columna", "Charlesdowniea edwardsii", "Chiropteridium lobospinosum", "Chytroeisphaeridia chytroeides", "Chytroeisphaeridia hyalina", "Cleistosphaeridium polypetellum", "Cleistosphaeridium varispinum", "Corrudinium harlandii", "Cribroperidinium tenuiceras", "Ctenidodinium cornigera",
 "Danea californica", "Danea impages", "Dapcodinium priscum", "Dichadogonyaulax culmula", "Dinogymnium albertii", "Diphyes ficusoides", "Distatodinium biffii", "Dracodinium condylos", "Dracodinium pachydermum", "Dracodinium rhomboideum", "Dracodinium varielongitudum", 
  "Ectosphaeropsis burdigalensis", "Endoscrinium galeritum", "Escharisphaeridia pocockii", "Enneadocysta arcuata",
  "Glaphyrocysta divaricata", "Glaphyrocysta semitecta", "Gonyaulacysta jurassica", "Gonyaulacysta pectinigera", "Glossodinium dimorphum", "Glaphyrocysta pastielsii", "Gonyaulacysta centriconnata", "Gonyaulacysta eisenackii",
  "Hystrichodinium furcatum", "Hemiplacophora semilunifera", "Herendeenia postprojecta", "Heterosphaeridium difficile", "Homotryblium floripes", "Homotryblium tasmaniense", "Hystrichokolpoma spinosum",
  "Kisselevia insolens", 
  "Leptodinium ambiguum", "Liasidium variabile", "Limbodinium absidatum", "Litosphaeridium arundum", "Litosphaeridium siphoniphorum", 
  "Mancodinium semitabulatum", "Manumiella druggii", "Membranilarnacia tenella", "Mendicodinium brunneum", "Mendicodinium microscabratum", 
 "Nelchinopsis kostromiensis", 
  "Occisocysta balios", "Ovoidinium cinctum", "Oligokolpoma galeotti", 
  "Pareodinia ceratophora", "Pareodinia prolongata", "Pseudoceratium pelliferum", "Palaeohystrichophora infusorioides", "Parvocysta bullala", "Phallocysta eumekes", "Prolixosphaeridium parvispinum", 
  "Rigaudella aemula", "Rhombodinium perforatum", 
  "Sepispinula ancorifera", "Spiniferites manumii", "Susadinium scofoides", "Stephanelytron redcliffense", "Schematophora obscura", "Schematophora speciosa", "Scriniocassis priscus", "Scriniodinium crystallinum", "Scriniodinium dictyotum", "Scriniodinium pharo", "Selenopemphix armageddonensis", "Senoniasphaera inornata", "Sirmiodiniopsis orbis", "Sirmiodinium grossi", "Spiniferites manumii", "Spiniferites ramosus", "Stiphrosphaeridium dictyophorum", 
  "Trichodinium scarburghensis", "Tubotuberella dangeardii", 
  "Unipontidinium aquaeductum", 
  "Valvaeodinium spinosum", "Valensiella ovulum",
  "Wanaea digitata", "Wanaea fimbriata", "Wanaea indotata", "Wanaea thysanota", "Rhombodinium draco", "Rhombodinium perforatum", "Wetzeliella gochtii", "Wetzeliella meckelfeldensis", "Wetzeliella samlandica", "Wilsonidinium ornatum")

#and the latitudinally synchronous LOs:
Lsp <- c(
  "Achomosphaera neptuni","Aldorfia aldorfensis", "Alisocysta margarita","Ambonosphaera calloviana", "Amiculosphaera umbracula", "Apteodinium granulatum", "Areoligera medusettiformis", "Areoligera tauloma", "Areosphaeridium diktyoplokum", "Atopodinium polygonale", "Atopodinium prostatum", "Apectodinium augustum", 
  "Batiacasphaera compta", "Biorbifera johnwingii", "Barssidinium graminosum", "Barssidinium pliocenicum", "Batiacasphaera minuta", "Batioladinium reticulatum", 
  "Carpatella cornuta", "Cerodinium diebelli", "Cerodinium striatum", "Cerodinium medcalfii", "Charlesdowniea columna", "Charlesdowniea edwardsii", "Cooksonidium capricornum", "Cordosphaeridium funiculatum", "Corrudinium devernalliae", "Corrudinium harlandii", "Cribroperidinium wetzelii", "Ctenidodinium continuum", "Cymosphaeridium validum",
 "Dapcodinium priscum", "Dichadogonyaulax culmula", "Dracodinium pachydermum", "Dracodinium rhomboideum", "Distatodinium biffi", "Dingodinium spinosum", "Dinogymnium albertii", 
  "Endoscrinium galeritum", "Eisenackia reticulata", "Enneadocysta multicornuta",
  "Fibradinium annetorpense", 
 "Glossodinium dimorphum", "Gonyaulacysta centriconnata", 
 "Hemiplacophora semilunifera", "Heteraulacacysta porosa",
 "Isabelidinium viborgense",
  "Kleithriasphaeridium corrugatum", "Kisselevia insolens", 
  "Labyrinthodinium truncatum", "Liasidium variabile", "Licracysta semicirculata", "Limbodinium absidatum", "Litosphaeridium arundum", "Litosphaeridium siphoniphorum", 
  "Mancodinium semitabulatum", "Manumiella druggii", "Membranilarnacia picena", "Membranilarnacia tenella", 
  "Odontochitina costata", "Operculodinium crassum",
  "Pareodinia prolongata", "Phoberocysta neocomica", "Pseudoceratium pelliferum", "Palaeoperidinium pyrophorum", "Phthanoperidinium comatum", "Palynodinium grallator", "Pseudoceratium pelliferum", 
  "Rhaetogonyaulax rhaetica", "Rhombodinium perforatum", 
 "Saturnodinium pansum", "Scriniocassis weberi", "Scriniocassis priscus", "Spiniferites manumii", "Spiniferites ramosus", "Stephanelytron redcliffense", "Susadinium scofoides", "Suessia swabiana", "Schematophora speciosa", "Scriniocassis priscus", "Senoniasphaera inornata", "Spiniferites manumii", "Stephodinium coronatum", 
  "Trichodinium scarburghensis", "Trithyrodinium evittii", "Trithyrodinium suspectum", 
  "Unipontidinium aquaeductum",
  "Valvaeodinium koessenium", 
  "Wanaea digitata", "Wanaea fimbriata", "Wanaea indotata", "Wanaea thysanota", "Wetzeliella gochtii", "Wetzeliella samlandica", "Wilsonidinium ornatum",  
  "Xenascus ceratoides")

FO_sp_s <- filter(FO_sp, taxa %in% Fsp)
LO_sp_s <- filter(LO_sp, taxa %in% Lsp)

FO_sp_s2 <- filter(FO_sp_s, Family=="Gonyaulacaceae, Leptodinioideae")
LO_sp_s2 <- filter(LO_sp_s, Family=="Gonyaulacaceae, Leptodinioideae")

FO_sp_s2
LO_sp_s2

FOn <- unique(FO_sp_s2$taxa)
LOn <- unique(LO_sp_s2$taxa)


```

```{r}
#this code will plot a PDF Age over paleolatitude of dinocyst events per family of dinocysts, consistent with Figure 5-28. Plots are stored on your computer (search for "Family_"), and will not show here.

for (i in unique(sp_dat1$Family)) {
  
  pdf(file=paste("Family_", i, ".pdf", sep=""))
  
  plot(ggplot()+
  geom_line(paleolat, mapping=aes(x=Age, y=Paleolatitude, group=location), size=0.4, orientation = "x", color = "grey", alpha=0.5)+
  geom_point(filter(FO_sp, Family==i), mapping=aes(x=Age, y=pal_lat), size=0.6, shape = 17)+
  geom_line(filter(FO_sp, Family==i), mapping=aes(x=Age, y=pal_lat, group=taxa), size=0.2, orientation = "y")+
  geom_point(filter(LO_sp, Family==i), mapping=aes(x=Age, y=pal_lat), size=0.6, shape = 19)+
  geom_line(filter(LO_sp, Family==i), mapping=aes(x=Age, y=pal_lat, group=taxa), size=0.2, linetype="longdash" , orientation = "y")+
   geom_line(filter(FO_sp_s, Family==i), mapping=aes(x=Age, y=pal_lat, group=taxa, color=taxa), size=0.6, orientation = "y")+
  geom_line(filter(LO_sp_s, Family==i), mapping=aes(x=Age, y=pal_lat, group=taxa, color=taxa), size=0.6, linetype="longdash", orientation = "y")+ 
    geom_point(filter(FO_sp_s, Family==i), mapping=aes(x=Age, y=pal_lat, group=taxa, color=taxa), size=0.6, shape = 17)+
    geom_point(filter(LO_sp_s, Family==i), mapping=aes(x=Age, y=pal_lat, group=taxa, color=taxa), size=0.6, shape = 19)+ 
  scale_x_continuous(name="Age (Ma; GTS2012)", breaks = seq(0, 250, 25), minor_breaks = seq(0, 250, 5), labels = seq(0, 250, 25))+
  scale_y_continuous(name = "Paleolatitude", breaks = seq(-90, 90, 30), minor_breaks = seq(-90, 90, 10), labels = seq(-90, 90, 30))+
  ggtitle(paste0("Family ", i))+
    coord_fixed(ratio=1)+
    theme_bw()+
    theme(legend.position = "bottom", legend.text = element_text(size=7, face="italic"))
  )
  
  dev.off()
  
}


```

```{r}
#this code will plot PDFs of modern species as in Figure 4 and in Supplement 2. plots will be saven on your computer, and will not show here:

for(i in unique(modernsp$taxa)){
 
  pdf(file=paste("modern_", i, ".pdf", sep=""))
  
  plot(ggplot()+
  geom_line(paleolat, mapping=aes(x=Age, y=Paleolatitude, group=location), orientation = "x", color = "grey", alpha=0.5)+
  geom_point(filter(modernsp, genus ==i), mapping=aes(x=Age, y=pal_lat), size=0.2, color = "red")+
  geom_point(filter(FO_sp, taxa==i), mapping=aes(x=Age, y=pal_lat), size=0.2, color = "blue")+
  geom_line(filter(FO_sp, taxa==i), mapping=aes(x=Age, y=pal_lat, group=taxa), size=0.2, color = "blue", orientation = "y")+
  geom_point(filter(LO_sp, taxa==i), mapping=aes(x=Age, y=pal_lat), size=0.2, color = "red")+
  geom_line(filter(LO_sp, taxa==i), mapping=aes(x=Age, y=pal_lat, group=taxa), size=0.2, color = "red", orientation = "y")+
  scale_x_continuous(name="Age (Ma; GTS2012)", breaks = seq(0, 250, 25), minor_breaks = seq(0, 250, 5), labels = seq(0, 250, 25))+
  scale_y_continuous(name = "Paleolatitude", breaks = seq(-90, 90, 30), minor_breaks = seq(-90, 90, 10), labels = seq(-90, 90, 30))+
    theme_bw()+
  ggtitle(paste0("Species ", i)))

dev.off()  
  
}

```

```{r}
#this code will plot PDFs per genus in the database. Ploits will be saved on your computer, and will not show here:

for(i in unique(sp_dat1$genus)){
 
  pdf(file=paste("Genus ", i, ".pdf", sep=""))
  
  plot(ggplot()+
  geom_line(paleolat, mapping=aes(x=Age, y=Paleolatitude, group=location), orientation = "x", color = "grey", alpha=0.5)+
  geom_point(filter(LO_sp, genus ==i), mapping=aes(x=Age, y=pal_lat), size=0.2, color = "red")+
  geom_line(filter(LO_sp, genus==i), mapping=aes(x=Age, y=pal_lat, group=taxa), size=0.2, color = "red", orientation = "y")+
  geom_point(filter(FO_sp, genus==i), mapping=aes(x=Age, y=pal_lat), size=0.2, color = "blue")+
  geom_line(filter(FO_sp, genus==i), mapping=aes(x=Age, y=pal_lat, group=taxa), size=0.2, color = "blue", orientation = "y")+
  scale_x_continuous(name="Age (Ma; GTS2012)", breaks = seq(0, 250, 25), minor_breaks = seq(0, 250, 5), labels = seq(0, 250, 25))+
  scale_y_continuous(name = "Paleolatitude", breaks = seq(-90, 90, 30), minor_breaks = seq(-90, 90, 10), labels = seq(-90, 90, 30))+
  ggtitle(paste0("Genus ", i)))

dev.off() 

}


```

```{r}
#this code will plot PDFs of all fossil species in the database, as shown in Supplement 3. plots will be saved on your computer, and will not show here:

for(i in unique(sp_dat1$taxa)){
 
  pdf(file=paste(i, ".pdf", sep=""))
  
  plot(ggplot()+
  geom_line(paleolat, mapping=aes(x=Age, y=Paleolatitude, group=location), orientation = "x", color = "grey", alpha=0.5)+
  geom_point(filter(LO_sp, taxa ==i), mapping=aes(x=Age, y=pal_lat), size=0.2, color = "red")+
  geom_line(filter(LO_sp, taxa==i), mapping=aes(x=Age, y=pal_lat, group=taxa), size=0.2, color = "red", orientation = "y")+
  geom_point(filter(FO_sp, taxa==i), mapping=aes(x=Age, y=pal_lat), size=0.2, color = "blue")+
  geom_line(filter(FO_sp, taxa==i), mapping=aes(x=Age, y=pal_lat, group=taxa), size=0.2, color = "blue", orientation = "y")+
  scale_x_continuous(name="Age (Ma; GTS2012)", breaks = seq(0, 250, 25), minor_breaks = seq(0, 250, 5), labels = seq(0, 250, 25))+
  scale_y_continuous(name = "Paleolatitude", breaks = seq(-90, 90, 30), minor_breaks = seq(-90, 90, 10), labels = seq(-90, 90, 30))+
  ggtitle(paste0("Species ", i)))

dev.off() 

}

```

```{r}
#Plots stratigraphic ranges of species per site. The plots will be stored on your computer, and not be stored here.


sp_dat
for(i in unique(sp_dat$location)){
  c_taxa <- filter(sp_dat, location == i)%>% count(taxa)
c_taxa <- nrow(c_taxa)

  pdf(file=paste("Site_", i, ".pdf", sep=""))

plot(ggplot(filter(sp_dat, location== i), mapping=aes(x=fct_reorder(taxa, Age, max, .desc=TRUE), y=Age))+
  geom_line()+
  geom_point(aes(shape=FO_LO), fill= "white")+
    scale_shape_manual(values = c(24, 25))+
    scale_y_continuous(trans="reverse")+
  theme_bw()+
  theme(axis.text.x = element_text(face= "italic", angle=90, hjust = 1, vjust=0.2, size = 4))+
    xlab("Species")+
    ylab("Age (Ma)")+
  ggtitle("Site ", i)
)

dev.off()

}


```


```{r}

sp_loc <- filter(sp_dat, location=="Suvlu")
sp_loc

c_taxa <- sp_loc%>% count(taxa)
c_taxa <- nrow(c_taxa)
c_taxa

                
sp_loc%>%
  mutate(taxa = fct_reorder(taxa, Age, max))%>%

ggplot(mapping=aes(x=taxa, y=Age))+
  geom_line()+
  geom_point(aes(shape=FO_LO), fill= "white")+
  scale_shape_manual(values = c(24, 25))+
  theme_bw()+
  theme(axis.text.x = element_text(face= "italic", angle=90, hjust = 1, vjust=0.2, size=4))

```

